-- liquibase formatted sql
-- changeset argus:1
create table public.app_user
(
    id               bigint primary key generated by default as identity,
    email            character varying(255),
    first_login_date timestamp without time zone,
    firstname        character varying(255),
    is_active        boolean,
    last_name        character varying(255),
    telegram_user_id bigint,
    user_name        character varying(255),
    user_state       text
);

create table public.raw_data
(
    id    bigint primary key generated by default as identity,
    event jsonb
);

create table public.binary_content
(
    id                     bigint primary key generated by default as identity,
    file_is_array_of_bytes bytea
);

create table public.app_document
(
    id                bigint primary key generated by default as identity,
    doc_name          character varying(255),
    file_size         bigint,
    mime_type         character varying(255),
    telegram_file_id  character varying(255),
    binary_content_id bigint,
    foreign key (binary_content_id) references public.binary_content (id)
        match simple on update no action on delete no action
);

create table public.app_photo
(
    id                bigint primary key generated by default as identity,
    file_size         integer,
    telegram_file_id  character varying(255),
    binary_content_id bigint,
    foreign key (binary_content_id) references public.binary_content (id)
        match simple on update no action on delete no action
);

